# render.yaml
# Blueprint untuk men-deploy aplikasi Laravel di Render.
# Simpan file ini di root direktori proyek Anda.

services:
  - type: pserv
    name: releaf_db25
    version: "14"
    region: singapore

  - type: web
    name: ReLeaf
    runtime: php
    plan: free
    region: singapore

    # Pengaturan Build & Start
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"

    healthCheckPath: /health

    envVars:
      - key: APP_KEY
        value: "base64:F6wHjhkdqtgCyoA4xN2GS+gTMxHls/ja/5dDgbDBEtM="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: releaf_db25
          property: connectionString
      - key: APP_URL
        fromService:
          type: web
          name: ReLeaf
          property: url
