name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main # Hanya berjalan saat ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 64000
          script: |
            # Masuk ke direktori proyek Anda di server
            cd /home/releafmy/repositories/ReLeaf

            # Tarik perubahan terbaru dari branch main
            git pull origin main

            # Install dependensi PHP (tanpa interaksi)
            composer install --no-interaction --prefer-dist --optimize-autoloader

            npm install
            npm run build

            php artisan storage:link

            # Jalankan migrasi database
            # Opsi --force diperlukan untuk lingkungan non-interaktif
            php artisan migrate --force

            php artisan optimize:clear

            # Optimasi cache untuk production
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
